"""add_relation

迁移 ID: 2ba09dd95dc6
父迁移:
创建时间: 2025-11-24 18:06:39.762777

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "2ba09dd95dc6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("nonebot_plugin_ai_groupmate",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("nonebot_plugin_ai_groupmate_userrelation",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("user_name", sa.String(), nullable=False),
    sa.Column("favorability", sa.Integer(), nullable=False),
    sa.Column("tags", sa.JSON(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_ai_groupmate_userrelation")),
    info={"bind_key": "nonebot_plugin_ai_groupmate"}
    )
    with op.batch_alter_table("nonebot_plugin_ai_groupmate_userrelation", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nonebot_plugin_ai_groupmate_userrelation_user_id"), ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_ai_groupmate_userrelation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nonebot_plugin_ai_groupmate_userrelation_user_id"))

    op.drop_table("nonebot_plugin_ai_groupmate_userrelation")
    # ### end Alembic commands ###
